Beleguic/ChallengeStack2

- www/Controllers/Auth.php
- www/Core/SQL.php
La connexion avec la Base de Données Supabase est bien effctué
> connexion to the online BDD

- www/Controllers/Auth.php
- www/Core/SQL.php
- www/Forms/Login.form.php
- www/Views/Auth/login.view.php
- www/Views/Main/home.view.php
Créeation du formulaire de login qui est en connexion avec les informations qui se trouve dans la BDD
> Login form with the BDD

- www/Views/Main/home.view.php
> add prefixe to conn flag

- package-lock.json
- package.json
- www/Views/front.tpl.php
> Add bootstrap

- www/Forms/Login.form.php
- www/Forms/Register.form.php
- www/Views/Partials/form.ptl.php
- www/index.php
- [ x] J'ai testé cette fonctionnalité localement et elle fonctionne comme prévu.
- [ x] Mes modifications sont conformes aux directives de contribution du projet.
> Change Form render, form config

- www/Views/front.tpl.php
- www/asset/css/main.css
- www/asset/css/style.css
- www/index.php
> Feat/front end/header template

- www/Controllers/Auth.php
- www/Core/Router.php
- www/Forms/Login.form.php
- www/Forms/Register.form.php
- www/Views/Auth/login.view.php
- www/Views/Auth/register.view.php
- www/index.php
> fix login form and register

- www/Core/Router.php
- www/Models/User.php
- www/index.php
> fix login and route

- www/Forms/Login.form.php
- www/Views/Partials/form.ptl.php
> Modif partial form, ajout d'id et class pour les bouton submit

- www/Forms/Login.form.php
- www/Views/Auth/login.view.php
- www/asset/css/bootstrap.css
> Fin du formulaire de connexion

- www/Controllers/Annonce.php
- www/Forms/Annonce.form.php
- www/Models/Annonce.php
- www/Models/v_Annonce.php
- www/Views/Annonce/annonce-view.view.php
- www/Views/Partials/form.ptl.php
> Add description to Annonce

- www/Views/Main/home.view.php
- www/Views/layout/front.tpl.php
- www/asset/css/bootstrap.css
- www/asset/css/style.css
> Fix/front end/template

- www/Views/Annonce/annonce-one.view.php
- www/Views/Main/home.view.php
> feat(annonce one): Page d'une seule annonce detaillé

- www/Core/Validator.php
- www/Views/Auth/register.view.php
> add more validaion in the register form

- www/Controllers/Auth.php
- www/Forms/Login.form.php
- www/Views/Auth/reset-pwd.view.php
- www/index.php
> Gestion du mot de passe oublié

- www/Controllers/Auth.php
- www/Core/Mailer.php
- www/Core/Validator.php
> add some change

- www/Controllers/Auth.php
- www/Core/Controller.php
- www/index.php
> fix synchro token

- www/Controllers/Annonce.php
- www/Forms/Login.form.php
- www/Views/Partials/form.ptl.php
> add reset button customisation in the form partial

- www/Forms/Login.form.php
- www/Views/Partials/form.ptl.php
> fix partial form, button reset

- www/Controllers/Newsletter.php
> Désabonner de la newsletter

- www/Controllers/Newsletter.php
- www/Core/SQL.php
- www/index.php
> fix newsletter subscribe and unscubsribe

- www/Controllers/Annonce.php
- www/Controllers/Auth.php
- www/Core/SQL.php
- www/Models/Annonce.php
- www/Models/User.php
- www/Views/Annonce/annonce-restore.view.php
- www/index.php
> add memento and restauration system on the annonce

- www/Controllers/Auth.php
- www/index.php
> fix activation redirection when creating new account

- www/Views/layout/back.tpl.php
> feat(lien-front): add front link in the back template

- www/Controllers/Annonce.php
- www/Core/SQL.php
- www/Views/Main/home.view.php
- www/Views/layout/front.tpl.php
- www/index.php
> add favori system

- www/Views/Main/home.view.php
- www/Views/layout/front.tpl.php
> feat(new-front-template): home page

- www/Controllers/Annonce.php
- www/Forms/Annonce.form.php
- www/Views/Annonce/annonce-photo.view.php
> add description of picture

- www/Controllers/Agent.php
- www/Views/Agent/agent1.view.php
- www/Views/Agent/agent2.view.php
- www/Views/Agent/agent3.view.php
- www/Views/Main/about-us.view.php
- www/Views/Main/home.view.php
- www/index.php
> feat(agents): add single agent pages

- www/Controllers/Annonce.php
- www/Views/Annonce/annonce-favorites.view.php
- www/Views/layout/front.tpl.php
- www/index.php
> feat(favorites): add view favorites

- www/Views/layout/front.tpl.php
> fix(front-template): fix UI navbar

- www/Controllers/Auth.php
- www/Core/SQL.php
> Check if mail alredy exist when a register is perform

- www/Controllers/Annonce.php
- www/Forms/Annonce.form.php
- www/Models/Annonce.php
- www/Models/AnnonceMemento.php
- www/Models/v_Annonce.php
- www/Views/Annonce/annonce-add.view.php
- www/Views/Annonce/annonce-update.view.php
- www/Views/Annonce/annonce-view.view.php
- www/Views/Partials/form.ptl.php
- www/config.php
> Change localisation system, Work now with the gov API 'adress'

- www/Views/layout/front.tpl.php
> fix(front-tpl): update name

- www/Controllers/Auth.php
- www/Core/Validator.php
- www/Views/Annonce/annonce-add.view.php
- www/Views/Auth/register.view.php
- www/Views/Partials/form.ptl.php
- www/Views/layout/front.tpl.php
> add popup system

- www/Controllers/Main.php
- www/Models/v_Annonce.php
- www/Views/Main/home.view.php
> Carrousel dynamique fini

- www/Views/Annonce/annonce-add.view.php
- www/Views/layout/back.tpl.php
> fix jquery in the back

- www/Controllers/Agent.php
- www/Views/Agent/agent-one.view.php
> add agent avis in the agent page one

- www/Views/Main/home.view.php
> Carroussel principale dorénavant renvoie bien vers sa propre annonce

- www/Views/Main/dashboard.view.php
- www/Views/layout/back.tpl.php
> feat(back-tpl): home page
